name = "convenience-store-sweets-bot"
main = "src/index.ts"
compatibility_date = "2023-12-01"


[[kv_namespaces]]
binding = "HONO_SWEETS"
id = "a5d85f3213b046e0b1f7b4c103ad3fd4"
preview_id = "d1137077c5334e38b29e910f92f35a85"

[triggers]
crons = ["0 2 * * 3"]

[[d1_databases]]
binding = "SWEETS_DB" # i.e. available in your Worker on env.DB
database_name = "convenience-store-sweets-d1"
database_id = "c00223d3-af95-4e9a-b4fa-12ed76016607"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"