name = "convenience-store-sweets-bot"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "HONO_SWEETS"
id = "a5d85f3213b046e0b1f7b4c103ad3fd4"
preview_id = "d1137077c5334e38b29e910f92f35a85"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"